name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: ['**']

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: '18'
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run build
